IDs = {
    btn_1: document.getElementById("btn_1"),
    btn_2: document.getElementById("btn_2"),
    btn_3: document.getElementById("btn_3"),
    section_1: document.getElementById("section_1"),
    section_2: document.getElementById("section_2"),
    section_3: document.getElementById("section_3"),
    section_A: document.getElementById("section_A"),
    section_B: document.getElementById("section_B"),
    btn_dema: document.getElementById("btn_dema"),
    time_line: document.getElementById("time_line"),
    Question_2: document.getElementById("question_2"),
      // buttons
    line: document.getElementById("line"),
    Q_2: document.getElementById("Q_2"),
    Q_3: document.getElementById("Q_3"),
    Q_4: document.getElementById("Q_4"),
    Q_5: document.getElementById("Q_5"),
    Q_6: document.getElementById("Q_6"),
    Q_7: document.getElementById("Q_7"),
    Q_8: document.getElementById("Q_8"),
    Q_9: document.getElementById("Q_9"),
    Q_10: document.getElementById("Q_10"),
    Q_11: document.getElementById("Q_11"),
    Q_12: document.getElementById("Q_12"),
    Q_13: document.getElementById("Q_13"),
    Q_14: document.getElementById("Q_14"),
    Q_15: document.getElementById("Q_15"),
    Q_16: document.getElementById("Q_16"),
    Q_17: document.getElementById("Q_17"),
    Q_18: document.getElementById("Q_18"),
    Q_19: document.getElementById("Q_19"),
    IQ_1: document.getElementById("IQ_1"),
    IQ_2: document.getElementById("IQ_2"),
    IQ_3: document.getElementById("IQ_3"),
    IQ_4: document.getElementById("IQ_4"),
    IQ_5: document.getElementById("IQ_5"),
//   Question section
    Question_1: document.getElementById("question_1"),
    Question_2: document.getElementById("question_2"),
    Question_3: document.getElementById("question_3"),
    Question_4: document.getElementById("question_4"),
    Question_5: document.getElementById("question_5"),
    Question_6: document.getElementById("question_6"),
    Question_7: document.getElementById("question_7"),
    Question_8: document.getElementById("question_8"),
    Question_9: document.getElementById("question_9"),
    Question_10: document.getElementById("question_10"),
    Question_11: document.getElementById("question_11"),
    Question_12: document.getElementById("question_12"),
    Question_13: document.getElementById("question_13"),
    Question_14: document.getElementById("question_14"),
    Question_15: document.getElementById("question_15"),
    Question_16: document.getElementById("question_16"),
    Question_17: document.getElementById("question_17"),
    Question_18: document.getElementById("question_18"),
    Question_19: document.getElementById("question_19"),
    Question_20: document.getElementById("question_I_1"),
    Question_21: document.getElementById("question_I_2"),
    Question_22: document.getElementById("question_I_3"),
    Question_23: document.getElementById("question_I_4"),

   
//    input Questions
    temp: document.getElementById("temp"),
    Age: document.getElementById("Age"),


}